apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-svc-{{ include "nginx-port-configurator.fullname" . }}
  labels:
    {{- include "nginx-port-configurator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["v1"]
    resources: ["services"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["kyverno.io/v1"]
    resources: ["clusterpolicies"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-ingress-{{ include "nginx-port-configurator.fullname" . }}
  namespace: {{ .Values.ingress.namespace }}
  labels:
    {{- include "nginx-port-configurator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["v1", "apps/v1"]
    resources: ["services", "deployments", "configmaps"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-svc-{{ include "nginx-port-configurator.fullname" . }}-rb
  labels:
    {{- include "nginx-port-configurator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: port-configurator-{{ include "nginx-port-configurator.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: access-svc-{{ include "nginx-port-configurator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-ingress-{{ include "nginx-port-configurator.fullname" . }}-rb
  namespace: {{ .Values.ingress.namespace }}
  labels:
    {{- include "nginx-port-configurator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: port-configurator-{{ include "nginx-port-configurator.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: access-ingress-{{ include "nginx-port-configurator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: port-configurator-{{ include "nginx-port-configurator.fullname" . }}-sa
  labels:
    {{- include "nginx-port-configurator.labels" . | nindent 4 }}
secrets:
  - name: port-configurator-{{ include "nginx-port-configurator.fullname" . }}-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: port-configurator-{{ include "nginx-port-configurator.fullname" . }}-secret
  labels:
    {{- include "nginx-port-configurator.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: port-configurator-{{ include "nginx-port-configurator.fullname" . }}-sa
type: kubernetes.io/service-account-token