apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-cm-{{ include "nginx-port-configurator.fullname" . }}
  labels:
    {{- include "nginx-port-configurator.labels" . | nindent 4 }}
data:
  INGRESS_NAMESPACE: {{ .Values.ingress.namespace }}
  INGRESS_DEPLOYMENT: {{ .Values.ingress.fullname }}
  {{- with .Values.envs }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
